name: Update voidlist
run-name: update-voidlist
on: 
  workflow_dispatch:
  push:
jobs:
  update-voidlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Update voidlist
        run: ./update-voidlist
      
      - name: Push to voids
        run: |
          git config --global user.name "Zero linux voidlist updater"
          git config --global user.email "zero-updater@zerolinux.dpdns.org"
          git remote set-url origin "https://x-access-token:${{ secrets.VOID_PUSH_TOKEN }}@github.com/0-linux/zero-voids.git"
          git add .
          git commit -m "Automatically updated voidlist.db"
          git push -u origin main
